### ISSUE TITLE
Multi-monitor support

### ISSUE THREAD

**Issue by ramb6** [ZHENYU64/ruler#1]
Thanks for making your protractor free to use. It really does emulate a transparent and easy to read protractor on the screen.

I am using two monitors, connected in extended mode. When running (only when it is running), regardless if protractor is held while pressing control or not, one of the screen turns black, with only the apple menu bar showing. The screen that turns black is not main one, and it seems like dragging the protractor to the other screen is not possible.

If I test for more I will update to see what fixes to identify. Thanks for looking into, and again thanks for making it free. 

Running 11.3, and recently downloaded the latest version as available on the app store.

**Comment by ZHENYU64** [comment]
Thanks for your feedback.

The black screen issue is fixed, and the new version is waiting for App Review of App Store.
It should be available within 12 hours. 

Please note the App only supports main display for now, but may have an upgrade later.

**Comment by ZHENYU64** [comment]
Thanks for your feedback.

Now the app supports multiple displays.

**Comment by ramb6** [comment]
Awesome, you got on it pretty quick too. Thanks for making it free and well designed
