### ISSUE TITLE
Multi-monitor support behavior

### ISSUE THREAD

**Issue by ramb6** [ZHENYU64/ruler#2]
Following up here as I was trying the ruler and now truly the second monitor does not black out anymore. 

The issue persists in that the ruler does not get dragged to the other monitor. The mouse cursor moves but as soon as it is on the second monitor, it disappears. Since it disappears I am unable to drag it back as it's no where to be found. 

If I find more ways that it can be replicated will be adding here.

**Comment by ZHENYU64** [comment]
Constrained by the api, Ruler cannot be dragged between monitors in the same way. Instead, we can switch between monitors with the dock menu.

Whether the environment is with single monitor or multiple monitors, the Ruler can be dragged out of the screen, and then, of course it cannot be dragged back. But some users may have to drag it to the edge of the screen during their work, so for now I cannot figure out a perfect & elegant way.

**Comment by ramb6** [comment]
Pointing that out made me realize the menu option from the dock. Adding that instruction in the tutorial window would be helpful, as the screenshot there does not include the 'Display on' menu. 

Sorry for pestering but I'd love to contribute to improvements. The design of the rulers feel as if they were built-in tools and thats amazing. Thanks again for making this : )
