### ISSUE TITLE
Unlock rotation

### ISSUE THREAD

**Issue by jekuno** [ZHENYU64/ruler#3]
It would be nice if the ruler and protractor could be rotated freely to all orientations. Currently in free rotation mode both tools can only be rotated 90° to the left or 90° to the right - starting from the original orientation.

This limitation should be removed so that the protractor can e.g. also be turned upside down in free rotation mode when needed.

**Comment by ZHENYU64** [comment]
Ruler is designed to be rotated freely, it should be able to rotate to any direction, like: ~15°, ~45°, ~70°.

Please check the preferences and choose you method you like to rotate with.
