### ISSUE TITLE
Specify a specifc degree to rotate the ruler or protractor

### ISSUE THREAD

**Issue by lingster** [ZHENYU64/ruler#4]
Currently you can only rotate the ruler by fixed 0/90/180/270 degrees. Could we have an option to input a specific value, like 49degrees?

**Comment by ZHENYU64** [comment]
Ruler is designed to be rotated freely, it should be able to rotate to any direction, like: ~15°, ~45°, ~70°.
Despite rotate freely, would you still need to input specific value?
