### ISSUE TITLE
protractor does not rotate

### ISSUE THREAD

**Issue by abcdef404** [ZHENYU64/ruler#9]
Hi,

I’m a maths tutor and purchased your ruler and protractor app to help with online teaching. While I appreciate the transparency feature, the lack of rotation makes it impossible to use for measuring angles and lines accurately. Adding a rotation feature would make these tools much more practical for the kind of measuring tasks I need for my lessons.

Thank you for considering this improvement!

Best wishes, Janet

**Comment by ZHENYU64** [comment]
Hi,

Thanks for your feedback.

Ruler and protractor can be rotated to any angle.

While activating the app (by default, holding Control key, and you should see a green indicator of icon on the dock)
rotate the ruler or protractor (by default, scroll on them, this is the touchpad gesture you use to move vertically in a webpage or a document, or similarly with a mouse).

You can also customize these settings in the Settings (Preferences) of app.
